<?php

/**
 * Implements hook_menu().
 */
function commerce_migrate_ubercart_menu() {
  $items['admin/content/migrate/ubercart_migration_options'] = array(
    'title' => 'Commerce Migrate Ubercart Options',
    'description' => 'Database and filesystem configuration for Commerce Migrate Ubercart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_migrate_ubercart_admin_form'),
    'access arguments' => array('migration information'),
    'weight' => 111,
  );
  return $items;
}

/*
 * Implements hook_migrate_api().
 */
function commerce_migrate_ubercart_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Administrative form to set migration options.
 */
function commerce_migrate_ubercart_admin_form($form, &$form_state) {
  $form['commerce_migrate_ubercart_source_database'] = array(
    '#type' => 'textfield',
    '#title' => t('Source database key in settings.php'),
    '#description' => t('The source database key in settings.php that describes an external database from which the import should be done. If left as "default" the default database will be used (and it must have all the Ubercart tables in it.)'),
    '#default_value' => variable_get('commerce_migrate_ubercart_source_database', 'default'),
  );
  $form['commerce_migrate_ubercart_public_files_directory'] = array(
    '#type' => 'textfield',
    '#title' => t('Relative or absolute path to the public files directory used for Ubercart images'),
    '#description' => t('Enter a path like /path/to/files which indicates where the source Ubercart files directory can be found.'),
    '#default_value' => variable_get('commerce_migrate_ubercart_public_files_directory', variable_get('file_public_path', 'sites/default/files')),
  );
  return system_settings_form($form);
}

/**
 * Make sure that we can actually access the database and directory provided
 */
function commerce_migrate_ubercart_admin_form_validate($form, &$form_state) {
  // Check to see whether we can access the database
  $migration_source_db = $form_state['values']['commerce_migrate_ubercart_source_database'];
  if (empty($GLOBALS['databases'][$migration_source_db])) {
    form_set_error('commerce_migrate_ubercart_source_database', t('The database key $databases["%key"] does not exist', array('%key' => $migration_source_db)));
  }
  else {
    try {
      $connection = Database::getConnection('default', $migration_source_db);
    }
    catch (Exception $e) {
      form_set_error('commerce_migrate_ubercart_source_database', t('The database key $databases["%key"] is not functional (Exception message %msg', array('%key' => $migration_source_db, '%msg' => $e->getMessage())));
    }
    $x = 1;
  }

  $ubercart_public_filepath = $form_state['values']['commerce_migrate_ubercart_public_files_directory'];

  if (!file_exists($ubercart_public_filepath)) {
    form_set_error('commerce_migrate_ubercart_public_files_directory', t('The directory %dir does not exist.', array('%dir' => $ubercart_public_filepath)));
  }
}
/**
 * Decide whether we have an external database and return the correct connection.
 *
 * If the migration source database exists, we will get a connection to it
 * instead of using the $databases['default'].
 */
function commerce_migrate_ubercart_get_source_connection() {
  $migration_source_db = variable_get('commerce_migrate_ubercart_source_database', 'default');
  if (empty($GLOBALS['databases'][$migration_source_db]['default'])) {
    $migration_source_db = NULL;
  }
  $connection = Database::getConnection('default', $migration_source_db);
  return $connection;
}

/**
 * Allow access to the public filepath.
 */
function commerce_migrate_ubercart_get_public_filepath() {
  $ubercart_public_filepath = variable_get('ubercart_public_filepath', variable_get('file_public_path', 'sites/default/files'));
  return $ubercart_public_filepath;
}